// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBE8XcSHYeOn8F44XETo_gZBv11dL_sCqU',
    appId: '1:975861240906:web:c32ef02fa92f40ac8202b3',
    messagingSenderId: '975861240906',
    projectId: 'realstate-12e4a',
    authDomain: 'realstate-12e4a.firebaseapp.com',
    storageBucket: 'realstate-12e4a.appspot.com',
    measurementId: 'G-Z6CZWY6RLZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLH5qXLALa10ftA0iykQb5oGciKoKiYDk',
    appId: '1:975861240906:android:d62ba31f24d403348202b3',
    messagingSenderId: '975861240906',
    projectId: 'realstate-12e4a',
    storageBucket: 'realstate-12e4a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRDn804UhCtQLa2LvuTXdKzLD0CmB0j8A',
    appId: '1:975861240906:ios:578c47cd3d6050c28202b3',
    messagingSenderId: '975861240906',
    projectId: 'realstate-12e4a',
    storageBucket: 'realstate-12e4a.appspot.com',
    iosBundleId: 'com.example.realstate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRDn804UhCtQLa2LvuTXdKzLD0CmB0j8A',
    appId: '1:975861240906:ios:578c47cd3d6050c28202b3',
    messagingSenderId: '975861240906',
    projectId: 'realstate-12e4a',
    storageBucket: 'realstate-12e4a.appspot.com',
    iosBundleId: 'com.example.realstate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBE8XcSHYeOn8F44XETo_gZBv11dL_sCqU',
    appId: '1:975861240906:web:f2fe08f5f46ea3278202b3',
    messagingSenderId: '975861240906',
    projectId: 'realstate-12e4a',
    authDomain: 'realstate-12e4a.firebaseapp.com',
    storageBucket: 'realstate-12e4a.appspot.com',
    measurementId: 'G-QRWWK0XMRD',
  );
}
